# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

# require:
#  - rubocop-rails
#  - rubocop-rspec

Metrics/ClassLength:
  Exclude:
    - app/models/ability.rb

Metrics/ModuleLength:
  Exclude:
    - app/helpers/application_helper.rb

# Apply rule to all cops
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'
