# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

ClassLength:
  Exclude:
    - app/models/ability.rb

ModuleLength:
  Exclude:
    - app/helpers/application_helper.rb

# Apply rule to all cops
AllCops:
  TargetRubyVersion: 2.0
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'
