version: '3'
services:
  web:
    image: tsp:latest
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DISPLAY: "${DISPLAY}"
  db:
    image: postgres:9.6
    restart: always
