name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        type: [coverage, features, helpers, mailer, models, rubocop]
    container: registry.opensuse.org/opensuse/infrastructure/tsp/containers/base:main

    steps:
    - name: Install bundler
      run: gem.ruby2.7 install bundler -v 1.17.3

    - uses: actions/checkout@v2

    - name: Cache ruby dependencies
      uses: actions/cache@v3
      with:
        path: |
          /usr/lib64/ruby/gems/
          /usr/bin/*ruby*
          /usr/bin/rake*
          /usr/bin/rails*
          /usr/bin/rspec*
        key: ${{ hashFiles('Gemfile.lock') }}

    - name: Install ruby dependencies
      run: bundler.ruby2.7 _1.17.3_ install

    - name: Set up the environment
      run: |
        cp config/database.test.yml config/database.yml
        cp config/site.example.yml config/site.yml
        bundler.ruby2.7 _1.17.3_ exec rake db:migrate RAILS_ENV=test

    - if: ${{ matrix.type == 'rubocop' }}
      name: Run rubocop
      run: bundler.ruby2.7 _1.17.3_ exec rubocop

    - if: ${{ contains(fromJson('["features", "helpers", "mailer", "models"]'), matrix.type) }}
      name: Run spec
      run: bundler.ruby2.7 _1.17.3_ exec rake spec spec/${{ matrix.type }}

    - if: ${{ matrix.type == 'coverage' }}
      name: Run spec
      run: bundler.ruby2.7 _1.17.3_ exec rake spec

    - if: ${{ matrix.type == 'coverage' }}
      name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
